#!/usr/bin/env python3
"""Extract pi(x) anchor constants from the tree's own sources.

Law-2 fixture rule (Phase 10.1.0 disposition 1): docs and gates cite this
fixture, never a hand-typed digit. Anchors are STRINGS (pi(1e19) exceeds
f64 integer range). Idempotent: re-running must byte-reproduce fixtures/pi.toml.
CI re-runs and diffs.

Sources (all in-tree):
  - crates/titan-count/src/gourdon_hetero.rs  (match arms 1e13..1e19)
  - assert_eq!(...count(N, ...), V) milestones across titan-count tests/bins
Usage: python3 scripts/extract_anchors.py  (run from repo root)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

PATTERNS = [
    # 10_000_000_000_000 => 346065536839,
    (re.compile(r"(\d[\d_]*)\s*=>\s*(\d[\d_]*)\s*,?"), lambda m: (m.group(1), m.group(2))),
    # assert_eq!(...count(100_000_000, 8), 5761455);
    (re.compile(r"count\(\s*(\d[\d_]*)\s*,[^)]*\)\s*,\s*(\d[\d_]*)"), lambda m: (m.group(1), m.group(2))),
    # (1_000_000_000, 50_847_534, "Tier 2 ...") tuples in tier probes
    (re.compile(r"\(\s*(\d[\d_]*)\s*,\s*(\d[\d_]*)\s*,\s*\"Tier"), lambda m: (m.group(1), m.group(2))),
    # run_ultra_scale(100_000_000_000_000_000, 2_623_557_157_654_233);
    (re.compile(r"run_ultra_scale\(\s*(\d[\d_]*)\s*,\s*(\d[\d_]*)\s*\)"), lambda m: (m.group(1), m.group(2))),
]


def norm(num: str) -> str:
    return num.replace("_", "")


def main() -> int:
    anchors: dict[int, str] = {}
    conflicts: list[str] = []
    files = list((ROOT / "crates").rglob("*.rs"))
    for path in sorted(files):
        try:
            text = path.read_text()
        except OSError:
            continue
        for rx, get in PATTERNS:
            for m in rx.finditer(text):
                xs, vs = get(m)
                try:
                    x = int(norm(xs))
                    v = norm(vs)
                except ValueError:
                    continue
                # Only powers of ten as keys.
                if x < 10 or set(str(x)[1:]) != {"0"}:
                    continue
                int(v)  # digits only
                rel = str(path.relative_to(ROOT))
                if x in anchors and anchors[x] != v:
                    conflicts.append(f"x={x}: {anchors[x]} vs {v} ({rel})")
                else:
                    anchors[x] = v
    if conflicts:
        print("ANCHOR CONFLICTS (refusing to write):", file=sys.stderr)
        for c in conflicts:
            print("  " + c, file=sys.stderr)
        return 1
    lines = [
        "# GENERATED by scripts/extract_anchors.py — do not hand-edit.",
        "# Values are strings: pi(1e19) exceeds f64 integer range.",
        "",
    ]
    for x in sorted(anchors):
        lines.append(f'"1e{len(str(x)) - 1}" = "{anchors[x]}"')
    out = ROOT / "fixtures" / "pi.toml"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(anchors)} anchors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
